name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: sudo apt-get install libopencv-dev libclang-dev -y --no-install-suggests --no-install-recommends && rustup update stable && rustup default stable
    - name: Build crate
      run: cargo build --verbose
